import type { ClaimRecord, ConflictRecord, EvidenceBundle, SourceRecord } from "./schema";

export const sources: readonly SourceRecord[] = [
  {
    sourceId: "SRC-HI-PVL-001",
    authority: "Hawaiʻi DCCA Professional and Vocational Licensing",
    title: "PVL home",
    canonicalUrl: "https://cca.hawaii.gov/pvl/",
    sourceType: "agency-instructions",
    professions: ["all"],
    jurisdiction: "Hawaiʻi",
    retrievedAt: "2026-09-07T00:00:00Z",
    retrievalMethod: "live page review",
    format: "html",
    accessibility: "HTML page; verify current accessibility at claim approval",
    fingerprint: "stage0-observed-src-hi-pvl-001",
    state: "observed",
    nextReviewAt: "2026-12-06T00:00:00Z",
    owner: "source-review lead",
  },
  {
    sourceId: "SRC-FED-DOJ-001",
    authority: "U.S. Department of Justice",
    title: "Professional License Portability",
    canonicalUrl: "https://www.justice.gov/servicemembers/professional-license-portability",
    sourceType: "enforcement-guidance",
    professions: ["all"],
    jurisdiction: "United States",
    retrievedAt: "2026-09-07T00:00:00Z",
    retrievalMethod: "live page review",
    format: "html",
    accessibility: "HTML page; verify current accessibility at claim approval",
    fingerprint: "stage0-observed-src-fed-doj-001",
    state: "needs-human-review",
    nextReviewAt: "2026-09-14T00:00:00Z",
    owner: "qualified source/legal reviewer",
  },
  {
    sourceId: "SRC-HI-PVL-002",
    authority: "Hawaiʻi DCCA Professional and Vocational Licensing",
    title: "Military Consumer Guide",
    canonicalUrl: "https://cca.hawaii.gov/wp-content/uploads/2024/11/Military-Consumer-Guide-Website.pdf",
    sourceType: "military-context",
    professions: ["all"],
    jurisdiction: "Hawaiʻi",
    retrievedAt: "2026-09-07T00:00:00Z",
    retrievalMethod: "search-indexed PDF; canonical URL rechecked",
    format: "pdf",
    accessibility: "Canonical URL returned 404 during Stage 0 review",
    fingerprint: "stage0-dead-src-hi-pvl-002",
    state: "dead",
    terminalAt: "2026-09-07T00:00:00Z",
    owner: "source-review lead",
  },
];

export const claims: readonly ClaimRecord[] = [
  {
    claimId: "CLM-HI-PVL-001",
    sourceId: "SRC-HI-PVL-001",
    proposition: "PVL provides a directory and separate board/program destinations.",
    locator: "Who We Are and quick-access sections",
    evidence: "Stage 0 observed page structure; not a routing approval.",
    applicability: "unsupported-profession starting point only after BL-004 approval",
    affectedProfessions: ["all"],
    state: "observed",
    conflictIds: [],
    nextReviewAt: "2026-12-06T00:00:00Z",
  },
  {
    claimId: "CLM-FED-001",
    sourceId: "SRC-FED-DOJ-001",
    proposition: "DOJ publishes current federal professional-license-portability guidance.",
    locator: "About Professional License Portability Under the SCRA and eligibility/application FAQs",
    evidence: "Stage 0 observed page content; federal/state conflict remains unresolved.",
    applicability: "evaluation fixture only until qualified source/legal review",
    affectedProfessions: ["all"],
    state: "needs-human-review",
    conflictIds: ["CONFLICT-001"],
    nextReviewAt: "2026-09-14T00:00:00Z",
  },
  {
    claimId: "CLM-HI-GUIDE-001",
    sourceId: "SRC-HI-PVL-002",
    proposition: "The dated state guide contains portability language that differs from updated federal guidance.",
    locator: "Portability Qualifications, PDF p. 33",
    evidence: "Search-indexed content only; canonical URL unavailable.",
    applicability: "conflict evidence only",
    affectedProfessions: ["all"],
    state: "dead",
    conflictIds: ["CONFLICT-001"],
    terminalAt: "2026-09-07T00:00:00Z",
  },
];

export const conflicts: readonly ConflictRecord[] = [
  {
    conflictId: "CONFLICT-001",
    sourceIds: ["SRC-FED-DOJ-001", "SRC-HI-PVL-002"],
    claimIds: ["CLM-FED-001", "CLM-HI-GUIDE-001"],
    issue: "Federal guidance changed after the dated Hawaiʻi guide; criteria, application framing, and source availability differ.",
    affectedRuleIds: [],
    detectedAt: "2026-09-07T00:00:00Z",
    owner: "qualified source/legal reviewer",
    state: "open",
    nextReviewAt: "2026-09-14T00:00:00Z",
    auditHistory: [
      {
        at: "2026-09-07T00:00:00Z",
        actor: "Stage 0 review",
        action: "opened conflict",
        evidence: "Canonical state PDF returned 404 and its indexed language differs from current DOJ guidance.",
      },
    ],
  },
];

export const observedEvidence: EvidenceBundle = { sources, claims, conflicts };
